version: '3.9'

services:
  slackbot-gpt-x:
    env_file:
      - .env
    image: "python:3.9"
    working_dir: /app
    volumes:
      - ./:/app/
    command: /bin/bash -c "pip install -r /app/requirements.txt && python /app/app.py"